### ISSUE TITLE
Add support for use with Headscale

### ISSUE THREAD

**Issue by cocallaw** [cocallaw/terraform-azure-tailscale-subnet-router#5]
An open source, self-hosted implementation of the Tailscale control server - https://github.com/juanfont/headscale

**Comment by cocallaw** [comment]
@sophware from your review and testing of the module, what changes should be made to support use with Headscale?

**Comment by sophware** [comment]
Just one optional parameter for login server url (control plane url).

Right now, the "tailscale up" command in tailscale-entrypoint.sh has mandatory variables for --hostname --authkey and --advertise-routes. An optional variable for --login-server would enable Headscale.

If not set, --login-server should not be passed at all. It should not be blank, nor should it attempt to default to the current Tailscale control plane servers (https://login.tailscale.com, https://controlplane.tailscale.com, and https://log.tailscale.com). Right now, those work, but this list "is likely to change, but infrequently" according to the following: 

https://tailscale.com/kb/1082/firewall-ports/

**Comment by cocallaw** [comment]
@sophware I have merged the changes from your PR https://github.com/cocallaw/terraform-azure-tailscale-subnet-router/pull/10 
Working on documentation updates before publishing a new release to TF Registry
